package:
  name: deltabit
  version: "1.0.0"  # Change this to your desired version

source:
  git_url: https://github.com/cbendett/deltabit.git
  git_rev: main

build:
  number: 0 # Increment with each new build
  scripts:
    - python=3.8.*
    - bin/deltabit
    - bash post-link.sh

requirements:
  run:
  - bioconda::gffpandas=1.2.2
  - conda-forge::pandas=2.3.0
  - conda-forge::biopython=1.85
  - conda-forge::seaborn=0.13.2
  - conda-forge::matplotlib=0.1.7
  - bioconda::mycotools=0.32.11
  - bioconda::busco=4.0.beta1
  - conda-forge::r-base=4.4.3
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-ggplot2=3.5.2
  - conda-forge::r-slider=0.3.2
  - conda-forge::r-ggextra=0.10.1
  - conda-forge::r-tidyr=1.3.1
  - conda-forge::r-ggpubr=0.6.0
  - conda-forge::r-readr=2.1.5
  - bioconda::bioconductor-pwalign
  - bioconda::bioconductor-biostrings


test:
  commands:
    - "deltabit_wrapper.sh --help"

about:
  home: "https://github.com/cbendett/deltabit
  summary: "Tool for detecting clusters of horizontally transferred genes"
